### ISSUE TITLE
Limit roles suggestion

### ISSUE THREAD

**Issue by TectonicGrinch** [barbarbar338/reaction-role#12]
I was wondering if it were possible to limit roles on the reaction like reactionRole.limit('messageid') to allow users to pick only one or however many reactions

**Comment by TectonicGrinch** [comment]
i think you said in discord that it cannot be done but am just adding it in as a suggestion

**Comment by barbarbar338** [comment]
Actually I have such an idea in mind but I can't find time to do it :)
I will add it soon :3

**Comment by barbarbar338** [comment]
With the new update, this feature will be added to the module in a few hours.
