### ISSUE TITLE
Reactions get removed after the message has been reacted with

### ISSUE THREAD

**Issue by SpikyZA** [barbarbar338/reaction-role#14]
Whenever a user reactes to the message, the role get given but the reaction gets removed
https://gyazo.com/3de7c4b9cbc54d5f90f1dd9ef9e1a1ef

**Comment by barbarbar338** [comment]
This is how the system works. When the "limited" option is set to "true" I have followed such a way to have only one of the options specified.

**Comment by SpikyZA** [comment]
👍 thanks
