### ISSUE TITLE
Add and Remove Roles

### ISSUE THREAD

**Issue by jasonanhvu** [barbarbar338/reaction-role#15]
Hey I'm wondering what I could implement coding-wise to make the bot remove user roles when the user toggles the reaction again. Just want a surefire method because my method's are quite ineffective and yours is very nice and nifty for my college gaming server.

**Comment by barbarbar338** [comment]
a lot of feature requests have been coming for a while. I'm working on a big update that contains everything you all want. I can fulfill this request with the new update in a few days
Have a nice day :)

**Comment by jasonanhvu** [comment]
Thank you so much! My server members will really appreciate it especially in these times.

**Comment by barbarbar338** [comment]
It was a little late, but I integrated the system.
However, there is a problem that it will change the syntax too much. Because an option will need to specify both the role to add and the role to remove.
