### ISSUE TITLE
Send user a Message on Reaction

### ISSUE THREAD

**Issue by SpikyZA** [barbarbar338/reaction-role#24]
This isnt really an issue but more of a suggestion

The possible implementation of when a user reacts, they get sent a message, either of a pre-determined contents or a custom one.

**Comment by barbarbar338** [comment]
Good idea! ı'll do it very soon

**Comment by barbarbar338** [comment]
I just integrated the system.
However, there is a problem that it will change the syntax too much. Because for each option, you need to set the message to be sent when a reaction is added and the message to be sent when the reaction is removed.
