### ISSUE TITLE
Give roles problems

### ISSUE THREAD

**Issue by FlavSnipy** [barbarbar338/reaction-role#25]
Hey !
Before my code worked, since yesterday I rebooted my bot and the code no longer works, I haven't changed anything yet.
The console displayed no errors ...

**Screens:**
[Screen1](https://media.discordapp.net/attachments/712032300606423163/771430491210907688/unknown.png)
[Screen2](https://media.discordapp.net/attachments/712032300606423163/771430728796864573/unknown.png)

Any solutions please ?

**Comment by barbarbar338** [comment]
yeah i saw that error and currently im working on it
thanks for report

**Comment by barbarbar338** [comment]
Use version 3.0.0 or higher
