### ISSUE TITLE
Role Issue ( doesnt give more than 1 role )

### ISSUE THREAD

**Issue by BlurryMeal** [barbarbar338/reaction-role#26]
**Describe the bug / error:**
So i have done the exact same things that the website displayed, but because of some reason when i react to one role it gives me that role but when i react to another it removes the previous one and gives me the new one even though the limit was set to 8 for example

**Expected behavior:**
i expected that the reaction roles will work and would give me as many roles i required

Code:
`const ReactionRole = require("reaction-role");
const system = new ReactionRole(process.env.TOKEN);

client.commands = new Discord.Collection();

const commandFiles = fs.readdirSync('./commands/').filter(file => file.endsWith('.js'));
for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	client.commands.set(command.name, command);
}

//reaction roles
let webdev_emoji = system.createOption("webdev:769472273941528587", "756417753044221972");
let design_emoji = system.createOption("design:770022122939613184", "756418048432275486");
let programming_emoji = system.createOption("progamming:769959123156467722", "756222780697215168");
let gaming_emoji = system.createOption("gaming:768177306794852418", "756417937048338454");
let gd_emoji = system.createOption("gd:769962692597121114", "756417923634954280");
let quiz_emoji = system.createOption("quiz:769942692293509160", "757466483247939616");
let photography_emoji = system.createOption("photography:768794075838414850", "756417791724224552");
let av_emoji = system.createOption("av:769944589335134239", "757476797221830657");

system.createMessage("771082393800933379", "757481161852321884", 8, null, webdev_emoji, design_emoji, programming_emoji, gaming_emoji, gd_emoji, quiz_emoji,photography_emoji,av_emoji);

system.init();`

**OS and Library Version:**
Just change the answers:
- OS version: Windows 10
- NodeJS version: v12.18.0
- DiscordJS version: v12.2.0

**Additional context**
i have added the token to an environment variable so that others wont be able to see it and is acting as a normal token so i dont think it is causing the issue.

**Comment by barbarbar338** [comment]
see #25 (fixed)
