### ISSUE TITLE
Role issue still not working

### ISSUE THREAD

**Issue by BlurryMeal** [barbarbar338/reaction-role#27]
you told me to use to version 3.0 and i am using that version now but for some reason it still isnt working.
i am facing the same issue in which if i react to an emoji i get the role but when i react to another i lose the previous role and get the new one.

**Comment by barbarbar338** [comment]
hmm i tested and it removes both
i'll fix it rn

**Comment by BlurryMeal** [comment]
ok ty

**Comment by barbarbar338** [comment]
For some reason I don't understand what is happening and how to fix it...
I might need some help. If someone knows how to fix it, feel free to open a pull request.

**Comment by barbarbar338** [comment]
I figured out what caused the error. Thanks to @KerimPotter :3
To use this package properly, you must turn on "SERVER MEMBERS INTENT" option. This is not a package-side problem, as a result of a new update by Discord.
![ReactionRoleWarningImage](https://raw.githubusercontent.com/barbarbar338/lib/master/personal_page/images/reaction-role-warning.png)
