### ISSUE TITLE
Monogdb Connection Issue

### ISSUE THREAD

**Issue by ritam110204** [barbarbar338/reaction-role#34]
When connecting the DB for reaction role with mongo URL its logging `MongoDBConnectionError: MongoParseError: Invalid connection string` in the console and it's not working.

![image](https://user-images.githubusercontent.com/66431066/97967638-81f48700-1de3-11eb-842d-64a0b7af4abf.png)
![image](https://user-images.githubusercontent.com/66431066/97967674-920c6680-1de3-11eb-81db-2014113213df.png)

**Comment by barbarbar338** [comment]
What is your reaction-role version? I'm using 3.1.0 and this works for me
```js
const ReactionRole = require("reaction-role");
const system = new ReactionRole(
    "token", 
    "mongodb+srv://rilp-bot:PASSWORD@rilp-bot.f1dpd.mongodb.net/DATABASE_NAME?retryWrites=true&w=majority"
);
system.init();
```

**Comment by ritam110204** [comment]
I installed the package today only. So I guess it will be the latest version only

**Comment by ritam110204** [comment]
Okay thnx it got connected, I had made a mistake
