### ISSUE TITLE
Not adding role 

### ISSUE THREAD

**Issue by typhoon11** [barbarbar338/reaction-role#35]
I did all the things but it's not adding a role when reacted and also not sending any dm.

```
const ReactionRole = require("reaction-role");
const system = new ReactionRole(
    process.env.BOT_TOKEN, 
    "mongodb+srv://rilp-bot:<PASSWORD>@rilp-bot.f1dpd.mongodb.net/reaction?retryWrites=true&w=majority"
  );  
const option = system.createOption("a:info:746298009691750451", "+", "-", [ "744951259626209295" ], []);
      
system.createMessage("773086208733609984", "744932703815860264", 1, [], option)
system.init()
```

**Comment by barbarbar338** [comment]
```js
const ReactionRole = require("reaction-role");
const system = new ReactionRole(
    "TOKEN", 
    "MONGODB URI"
);  
const option = system.createOption("wushang:754801855174803543", "+", "-", [ "714542230135767060" ], []);
      
system.createMessage("773444733963730984", "717628563813171260", 1, [], option)
system.init()
```
this one works for me?

**Comment by ritam110204** [comment]
No working for me Whippy your staff also checked my joining my server and he checked my code also

**Comment by ritam110204** [comment]
My Code :
![image](https://user-images.githubusercontent.com/66431066/98081927-f855bf80-1e9d-11eb-986c-63c473b54361.png)
Console :
![image](https://user-images.githubusercontent.com/66431066/98081971-0c012600-1e9e-11eb-8dad-9f37c9d0eaf9.png)
Video Proof : 
https://www.100free.com/view?v=3149760319

**Comment by barbarbar338** [comment]
I will leave this issue open for now

Limitations came to most things since discord's recent update. The reason your codes are not working right now is due to module and discord. I am looking for a solution. Module will continue to give these errors until a solution is found. To be more accurate, the reason for the errors you are facing right now is due to the new bot policies of discord.

**Comment by barbarbar338** [comment]
I believe everything about this error is fixed. You can use reaction-role@3.2.0.
