### ISSUE TITLE
Roles giving/removed

### ISSUE THREAD

**Issue by HypaCNH** [barbarbar338/reaction-role#37]
If you add more then 1 role option and want to add both roles always 1 gets removed. Any fix?
and yes  server members intent is turned on. 
![image](https://user-images.githubusercontent.com/72663865/98439490-7ad6bd00-20f2-11eb-93f7-536339bccb03.png)

**Comment by HypaCNH** [comment]
Also cant add a role if the emojis is animated.

**Comment by barbarbar338** [comment]
#35
