### ISSUE TITLE
TypeError: option.remove is not iterable

### ISSUE THREAD

**Issue by michaelrosstarr** [barbarbar338/reaction-role#38]
Heyya!
Hope you are doing well.

So, im getting error in console. 
`TypeError: option.remove is not iterable`
I don't know if im just being stupid or what.

Any suggestions that you can give to resolve this?

**Comment by barbarbar338** [comment]
Can i see your code?

**Comment by michaelrosstarr** [comment]
Ill send it now

**Comment by michaelrosstarr** [comment]
`const { ReactionRole } = require("reaction-role");
const system = new ReactionRole(process.env.TOKEN);

const member = system.createOption("✅","You were verified", "You were unverified" ["602418819939434512"],["602418819939434512"]);
system.createMessage("676445425401724949", "654251380231372810", 2, [], member);

const news = system.createOption("📰","You got the News Role", "You removed the News Role", ["680882214631899186"],["680882214631899186"]);
const streamers = system.createOption("📺","You got the Streamer Alert Role", "You removed the Streamer Alert Role", ["602418820396613642"],["602418820396613642"]);
const warning = system.createOption("⚠️","You got the Notifications Role", "You removed the Notifications Role", ["736967373256392814"],["736967373256392814"]);
const giveaways = system.createOption("🎉", "You got the Giveaways Role", "You removed the Giveaways Role", ["736967313487560775"],["736967313487560775"]);
system.createMessage("736982676397096981", "680879327021498415", 4, [], news, streamers, warning, giveaways);

let arkse = system.createOption("ark:696693582324695132","You recieved a Game Role","You removed a Game Role", ["696688631796072528"],["696688631796072528"]);
let rust = system.createOption("rust:696692277480783893","You recieved a Game Role","You removed a Game Role", ["696689245363896350"],["696689245363896350"]);
let minecraft = system.createOption("mc:696692303603171449","You recieved a Game Role","You removed a Game Role", ["696689264099852368"],["696689264099852368"]);
let minecraftjava = system.createOption("bedrock:727978008681381978","You recieved a Game Role","You removed a Game Role", ["736972474708787340"],["736972474708787340"]);
let conanexiles = system.createOption("conanexiles:696692302403600414","You recieved a Game Role","You removed a Game Role", ["696689332609613885"],["696689332609613885"]);
let sevenDaysToDie = system.createOption("7d2d:696693581607600129","You recieved a Game Role","You removed a Game Role", ["696689356714541157"],["696689356714541157"]);
let csgo = system.createOption("csgo:696692283160133732","You recieved a Game Role","You removed a Game Role", ["696689392777035808"],["696689392777035808"]);
let insurgencysandstorm = system.createOption("si:696693587563511868","You recieved a Game Role","You removed a Game Role", ["696689409847984158"],["696689409847984158"]);
let teamfortressTwo = system.createOption("tf2:696692282333855754","You recieved a Game Role","You removed a Game Role", ["696689453581860894"],["696689453581860894"]);
let arma3 = system.createOption("arma3:696692301484916846","You recieved a Game Role","You removed a Game Role", ["696689497240502382"],["696689497240502382"]);
let mordhau = system.createOption("mordhau:696692308510375946","You recieved a Game Role","You removed a Game Role", ["696689540513005608"],["696689540513005608"]);
let gmod = system.createOption("gmod:696692284762095667","You recieved a Game Role","You removed a Game Role", ["696689646993932289"],["696689646993932289"]);
let killingFloorTwo = system.createOption("kf2:696692300595724298","You recieved a Game Role","You removed a Game Role", ["696689681936416839"],["696689681936416839"]);
let theForest = system.createOption("forest:696692308317306951","You recieved a Game Role","You removed a Game Role", ["696689743160672276"],["696689743160672276"]);
let leftFourDeadTwo = system.createOption("l4d2:696692303795847188","You recieved a Game Role","You removed a Game Role", ["696689867228184637"],["696689867228184637"]);
let unturned = system.createOption("unturned:696692277564801074","You recieved a Game Role","You removed a Game Role", ["696689894931562496"],["696689894931562496"]);
let acc = system.createOption("ACC:708850589534126122","You recieved a Game Role","You removed a Game Role", ["736974586712948860"],["736974586712948860"]);
let astroneer = system.createOption("astroneer:727980550882852916","You recieved a Game Role","You removed a Game Role", ["736974602663886922"],["736974602663886922"]);
let darklight = system.createOption("darkandlight:765163538447990785","You recieved a Game Role","You removed a Game Role", ["765164290616590355"],["765164290616590355"]);
system.createMessage("765163770364166184", "680879327021498415", 19, [], arkse, rust, minecraft, minecraftjava, conanexiles, sevenDaysToDie, csgo, insurgencysandstorm, teamfortressTwo, arma3, mordhau, gmod, killingFloorTwo, theForest, leftFourDeadTwo, unturned, acc, astroneer, darklight);

system.init();
`

**Comment by michaelrosstarr** [comment]
as far as i know, and what i looked at, the old formatting (on one line) should still work, unless im being real thick

**Comment by barbarbar338** [comment]
well, I double checked but did not see any problems. Are you sure there are no typos?

**Comment by michaelrosstarr** [comment]
Yeah, ill just do a double check now, just incase

**Comment by michaelrosstarr** [comment]
Fixed it, i was just being dumb. I left out a , ...

Thank for the help tho!
