### ISSUE TITLE
Limit Issue

### ISSUE THREAD

**Issue by jdoesplay** [barbarbar338/reaction-role#39]
I tried getting help on the Discord server and I was unable. I then did some searching about my issue and saw someone else posted about it on 12/21 with not a ton of response either, so I figured it would make sense to post in the issues. The only issue is that reaction-role doesn't prevent users from reacting a second time to a message that has a limit. So, if the limit is 1, I can still react to the other options and it will raise the counter but just won't give the role. It does, however, send me the reaction-remove message any time I un-react. It's really just a visual bug from what I can see, but definitely slightly annoying. Hopefully there is a fix that can be made!

**Comment by barbarbar338** [comment]
Yes, we are aware of this error and we are trying to prevent it. Thanks for reporting :)

I'm leaving this issue open for now

**Comment by barbarbar338** [comment]
Fixed with latest commit
