### ISSUE TITLE
Sending Reaction Role message when a command is run

### ISSUE THREAD

**Issue by StoneMcYT** [barbarbar338/reaction-role#40]
How do i make it so when someone does
prefix + rr
it sends the reaction message

Lilke i want to put it in an embed

**Comment by barbarbar338** [comment]
i really don't understand what you want to do

**Comment by StoneMcYT** [comment]
> i really don't understand what you want to do
I hope the photo explains what i kind of want to do
![image](https://user-images.githubusercontent.com/67421882/111068905-99681d00-8505-11eb-9324-095ebff02c43.png)

**Comment by barbarbar338** [comment]
Just send an embed message with bot to channel and copy it's id
