### ISSUE TITLE
Reaction not showing 

### ISSUE THREAD

**Issue by StoneMcYT** [barbarbar338/reaction-role#41]
So this is my code and somehow it didnt add any rections to my message
![image](https://user-images.githubusercontent.com/67421882/111068753-08914180-8505-11eb-9ad5-519b46c87bfb.png)

```
const { ReactionRole } = require("reaction-role");
const client = new ReactionRole("BOTTOKEN");
	
const option1 = client.createOption(
		":100:",
		"Role Added",
		"Role Removed",
		["781629929246162964"],
	);
const option2 = client.createOption(
		":smile:",
		"StoneMc tests Role added",
		"StoneMc tests role removed",
		["820562935113056257"],
	);
	
const LIMIT = 2	
const RESTRICTIONS = [];
	
client.createMessage(
		"820633616710893579",
		"820289056972996618",
		LIMIT,
		RESTRICTIONS,
		option1,
		option2,
	);
	
client.init();
```

**Comment by StoneMcYT** [comment]
after looking through my code i somehow got this 
![image](https://user-images.githubusercontent.com/67421882/111069380-d3d2b980-8507-11eb-86fe-bafa8882a8b1.png)

well my code is here
https://sourceb.in/VTqDmThwjH

**Comment by barbarbar338** [comment]
You are using DiscordJS.Client, use ReactionRole as you client. See https://hastepaste.xyz/tr/1f0oh4ou68e
