### ISSUE TITLE
Reaction Types

### ISSUE THREAD

**Issue by Justman10000** [barbarbar338/reaction-role#42]
With this issue, I suggest reaction types of the following types:

- Normal (Already)
- Once (Adds the user to the user, however, directly removes their reaction)
- Remove (Takes a user a role)
- Voice (Gives a user a role as soon as it is in a voice channel)
- DM (Notifies the user via PN when he gets a roleI)

All informations [here](https://docs.zira.bot)...

Exampel:

const { ReactionRole } = require("reaction-role");
const system = new ReactionRole("YOUR_BOT_TOKEN");

// use a mongodb uri if you want persistent messages
const system = new ReactionRole("YOUR_BOT_TOKEN", "MONGODB_URI");

// create simple option
const option1 = system.createOption("emoji", ["role_id", "role_id"]);

// create option with messages
const option2 = system.createOption(
	"emoji",
	["role_id"],
	"You got a role", // add message
	"removed role", // remove message
);

// create message
system.createMessage(
	"channel_id",
	"message_id",
	1, // reaction limit
        Normal // reaction type
	option1,
);

system.init();

**Comment by Justman10000** [comment]
When are you finished here?

**Comment by barbarbar338** [comment]
I haven't been able to work on it yet due to several personal circumstances.

**Comment by Justman10000** [comment]
> 
> 
> I haven't been able to work on it yet due to several personal circumstances.

When will you start? I need this so often 😅

**Comment by Justman10000** [comment]
@barbarbar338

**Comment by barbarbar338** [comment]
you can follow here https://338.rocks/git/reaction-role/

**Comment by barbarbar338** [comment]
Implemented with commit 35c7bf41a87d02b735f5160b91d4100ace41c066
