### ISSUE TITLE
Reaction execute code

### ISSUE THREAD

**Issue by Justman10000** [barbarbar338/reaction-role#43]
This issue includes the following:

Another emoji type that executes code, with which it would be possible, for example, to open a ticket via reactions (the already suggested type **_Once_** would be necessary here)...

**Comment by barbarbar338** [comment]
Looks like a good idea but seems out of purpose of the package

**Comment by Justman10000** [comment]
> 
> 
> Looks like a good idea but seems out of purpose of the package

How?

**Comment by barbarbar338** [comment]
The purpose of the package is to give users a role

**Comment by Justman10000** [comment]
Not necessarily, it's called reaction role, you can also execute codes through reactions ...

**Comment by barbarbar338** [comment]
well i can do it but as i said it seems out of purpose of the package

**Comment by Justman10000** [comment]
Hmm

**Comment by Justman10000** [comment]
It would be pretty nice anyway

**Comment by Justman10000** [comment]
@barbarbar338

And?

**Comment by barbarbar338** [comment]
i'll start working on it rn

**Comment by barbarbar338** [comment]
Implemented with commit ddab90a0d1d50c8cecdee13ff493400a8d96dacf
