### ISSUE TITLE
How to add new reaction roles after init()?

### ISSUE THREAD

**Issue by zoli456** [barbarbar338/reaction-role#45]
How to add new reaction roles after init()? I need to restart the bot everytime I set up a reaction role.

**Comment by barbarbar338** [comment]
Are you sure that the bot is not seeing the newly added reaction role? Because it should fetch them from database. Also can you send me your code so that I can reproduce the problem and try to fix it. <3

**Comment by zoli456** [comment]
This is my code: https://pastebin.com/bFXachdp
I use the lastest Discord js 14.11.0

**Comment by zoli456** [comment]
I want to edit the reactions roles after calling the init(). I reset the database back to emtpy and i try to add a reaction role to a message but it only work after the bot restart.

**Comment by zoli456** [comment]
I integrated the whole package into my bot. It solved the problem.
