### ISSUE TITLE
Emoji must be a string or GuildEmoji/ReactionEmoji

### ISSUE THREAD

**Issue by SpikyZA** [barbarbar338/reaction-role#6]
Hello

I am getting this error in console: `UnhandledPromiseRejectionWarning: TypeError [EMOJI_TYPE]: Emoji must be a string or GuildEmoji/ReactionEmoji`

and this is my code: let option1 = reactionRole.createOption("✅", "id", "id");
there is the actual ID in the code, I am just not comfortable sharing it

**Comment by barbarbar338** [comment]
Unfortunately I have no idea about this problem. Please can you try another emoji and let me know Even better if you try using a custom emoji. :3

**Comment by barbarbar338** [comment]
I just used the code I mentioned below and had no problems. Can you try reinstallling the module?
You can do it like this => `npm uninstall reaction-role` and then `npm install reaction-role`
I will be happy if you inform me after these are tried

`
const ReactionRole = require("./reactionRole");
const reactionRole = new ReactionRole.Main("TOKEN");
let option1 = reactionRole.createOption("✅", "ROLE_ID");
reactionRole.createMessage("MESSAGE_ID", "CHANNEL_ID", option1);
reactionRole.init();
`

**Comment by SpikyZA** [comment]
Okay dokie. I will do all of that today

**Comment by SpikyZA** [comment]
It's weird, cause it works on my one bot but not on the other

**Comment by barbarbar338** [comment]
What is your Discord.js version? Must be giving an error because your Discord.js is under version 12. This module uses Discord.js v12. Will you try again after updating your discord.js version and let me know :)

**Comment by SpikyZA** [comment]
Ok. So my old bot is still running v11 but with the non v12 of role reaction

My new one is running everything latest. Still the same bug. I'll do another bot and see

**Comment by barbarbar338** [comment]
Do you have a chance to send the code you use to me in some way?

**Comment by SpikyZA** [comment]
I can't atm. I can send it tomorrow morning (I'm GMT+2)

**Comment by barbarbar338** [comment]
I think your problem has been fixed

**Comment by SpikyZA** [comment]
Sorry I did not get to you earlier. It has been a hectic few days. I was evacuated out of my University Residence. I'm sorry about that

**Comment by barbarbar338** [comment]
no problem.  We are all in such a situation right now.

**Comment by SpikyZA** [comment]
Thank for understanding :)

So i updated everything and it still gives me that original error
here is the full code:
`const ReactionRole = require("reaction-role");
const reactionRole = new ReactionRole.Main(client);

let option1 = reactionRole.createOption("✅", "688393398272655362", "688393351598440452");

reactionRole.createMessage("688390147301048435", "683458608612245533", false, option1);

reactionRole.init();`,
if you want the full code, can i rather email or discord PM it to you?

**Comment by SpikyZA** [comment]
DUUUUDE,it works but only with one roleid, as soon as i add a 2nd role ID, it doesnt want to work

**Comment by barbarbar338** [comment]
oh i understand! you don't need to use "false" argument anymore :D just use this function => reactionRole.createMessage("message_id", "channel_id", option, option2...). O just removed this argument because it causes lot's of errors ;) can you try this and let me know :)

**Comment by SpikyZA** [comment]
Ok. Will check.

**Comment by barbarbar338** [comment]
what caused this error is that we removed the "DISJOINT" boolean value in older versions. naturally it detects the value of "true" or "false" that you specify as an "option" and cannot find an emoji of this option. if you want to use this value again, you can use v1.5.1 (not recommended)

**Comment by SpikyZA** [comment]
Awesome. Thanks for the help ✊
